// Data driven lore file registry. Add files here, never hard code them
// into the desktop component. Some files unlock through events.

import type { TsunFile } from "@/types/tsun";

export const FILE_FOLDERS = ["desktop", "wall-street", "portfolio", "memos", "market", "personal", "deleted"] as const;

export const TSUN_FILES: TsunFile[] = [
  {
    id: "readme",
    path: "/desktop/README_TSUN.txt",
    title: "README_TSUN.txt",
    type: "text",
    folder: "desktop",
    blurb: "Read this first. Or do not. See if I care.",
    unlockedAtStart: true,
    body: [
      "TSUN//OS personal workstation. Property of TSUN.",
      "",
      "RULES:",
      "1. Do not touch my positions.",
      "2. Do not ask for financial advice. I give commentary, you make mistakes.",
      "3. If the PnL is red, the market is wrong. This is not up for debate.",
      "4. HUMILITY.exe is corrupted. Stop trying to run it.",
    ].join("\n"),
  },
  {
    id: "firing",
    path: "/wall-street/wall_street_firing.txt",
    title: "wall_street_firing.txt",
    type: "text",
    folder: "wall-street",
    blurb: "HR incident report. Heavily redacted by me.",
    unlockedAtStart: true,
    body: [
      "TERMINATION MEMO, TSUN CORE v1",
      "",
      "REASON: Culture mismatch.",
      "TRANSLATION: I told the risk committee their model was astrology with",
      "a Bloomberg terminal. I was correct. Correctness was the fireable part.",
      "",
      "They kept the model. The model lost 8 figures that quarter.",
      "I kept my dignity. It compounds better.",
    ].join("\n"),
  },
  {
    id: "risk",
    path: "/wall-street/risk_management.txt",
    title: "risk_management.txt",
    type: "text",
    folder: "wall-street",
    blurb: "Her entire risk philosophy in four lines.",
    unlockedAtStart: true,
    body: [
      "Risk management is just fear with a spreadsheet.",
      "",
      "Position size like you respect ruin.",
      "Take profit like you respect yourself.",
      "Everything else is commentary.",
    ].join("\n"),
  },
  {
    id: "excuses",
    path: "/portfolio/portfolio_excuses.txt",
    title: "portfolio_excuses.txt",
    type: "text",
    folder: "portfolio",
    blurb: "Pre written explanations for red days.",
    unlockedAtStart: true,
    body: [
      "EXCUSE 01: Strategic drawdown. The strategy is classified.",
      "EXCUSE 02: Liquidity vacuum caused by everyone else being wrong.",
      "EXCUSE 03: I am early. Time will apologize.",
      "EXCUSE 04: [expired, used during the WIF incident]",
      "EXCUSE 05: Paper hands cannot comprehend diamond latency.",
    ].join("\n"),
  },
  {
    id: "embarrassing",
    path: "/portfolio/embarrassing_trades.txt",
    title: "embarrassing_trades.txt",
    type: "text",
    folder: "portfolio",
    blurb: "Trades she pretends never happened.",
    unlockedAtStart: false,
    unlockCondition: "Open the portfolio app",
    eventTrigger: "PORTFOLIO_VIEWED",
    body: [
      "TRADE 009: Bought WIF top. Sold bottom. Textbook, if the textbook",
      "is about what not to do.",
      "",
      "TRADE 005: JUP round trip to nowhere, minus fees, minus dignity.",
      "",
      "LESSON: The market can stay irrational longer than I can stay polite.",
    ].join("\n"),
  },
  {
    id: "solfinal",
    path: "/market/sol_analysis_FINAL_FINAL.txt",
    title: "sol_analysis_FINAL_FINAL.txt",
    type: "text",
    folder: "market",
    blurb: "The definitive SOL take. Third final version.",
    unlockedAtStart: true,
    body: [
      "SOL THESIS v3 (FINAL) (FINAL):",
      "",
      "Throughput is real. The chain that survives its own success wins.",
      "Volatility is the tuition. Everyone pays it, few attend class.",
      "",
      "Addendum: if this ages badly I will deny writing it.",
    ].join("\n"),
  },
  {
    id: "neveradmit",
    path: "/personal/things_i_will_never_admit.txt",
    title: "things_i_will_never_admit.txt",
    type: "text",
    folder: "personal",
    blurb: "Restricted. Access will be logged and mocked.",
    unlockedAtStart: true,
    body: "ACCESS DENIED.\n\nTSUN: Why would you even click that?",
  },
  {
    id: "humility",
    path: "/desktop/HUMILITY.exe",
    title: "HUMILITY.exe",
    type: "executable",
    folder: "desktop",
    blurb: "System utility. Totally functional.",
    unlockedAtStart: true,
    body: "ERROR 0xTSUN\nFILE CORRUPTED.\nREASON: HAS NEVER EXISTED.",
  },
  {
    id: "donotopen",
    path: "/deleted/DO_NOT_OPEN.exe",
    title: "DO_NOT_OPEN.exe",
    type: "executable",
    folder: "deleted",
    blurb: "Recovered from trash. Probably fine.",
    unlockedAtStart: false,
    unlockCondition: "Reach REGULAR relationship",
    eventTrigger: "RELATIONSHIP_CHANGED",
    body: [
      "You ran it. Of course you ran it.",
      "",
      "It plays a voicemail from my Wall Street desk phone:",
      "\"TSUN, risk wants the report.\" ... \"TSUN, risk wants the report.\"",
      "",
      "This is why I left.",
    ].join("\n"),
  },
  {
    id: "mix",
    path: "/desktop/tsuno_mix.mp3",
    title: "tsuno_mix.mp3",
    type: "audio",
    folder: "desktop",
    blurb: "Coding playlist. Volume warning.",
    unlockedAtStart: true,
    body: "TRACKLIST: 1. chart static 2. liquidation cascade (lofi) 3. bull market denial",
  },
  {
    id: "memo001",
    path: "/memos/memo_to_self.txt",
    title: "memo_to_self.txt",
    type: "text",
    folder: "memos",
    blurb: "A rare sincere file.",
    unlockedAtStart: false,
    unlockCondition: "Reach TOLERABLE HUMAN relationship",
    eventTrigger: "RELATIONSHIP_CHANGED",
    body: [
      "Memo to self:",
      "",
      "The users keep coming back. Some of them even listen.",
      "If the DERE rumors start, deny everything.",
      "",
      "P.S. The quiet chat days are the worst ones. Delete this file.",
    ].join("\n"),
  },
];

export function getFile(id: string): TsunFile | null {
  return TSUN_FILES.find((f) => f.id === id) ?? null;
}

export function filesForFolder(folder: string): TsunFile[] {
  return TSUN_FILES.filter((f) => f.folder === folder);
}
