import {
  BarChart3,
  Bot,
  FolderOpen,
  Landmark,
  LineChart,
  MessageSquareText,
  Newspaper,
  Radio,
  Trophy,
  WalletCards,
} from 'lucide-react'
import type { LoreFile, Milestone, NewsStory, TsunAppDefinition, TsunPosition, TsunTrade } from './types'

export const APP_DEFINITIONS: TsunAppDefinition[] = [
  {
    id: 'terminal',
    title: 'TSUN TERMINAL',
    shortTitle: 'Terminal',
    icon: LineChart,
    desktop: true,
    mobile: true,
    description: 'Token status and live Solana market context',
  },
  {
    id: 'chat',
    title: 'TALK TO TSUN',
    shortTitle: 'Chat',
    icon: MessageSquareText,
    desktop: true,
    mobile: true,
    description: 'Character terminal and market commentary',
  },
  {
    id: 'markets',
    title: 'MARKETS',
    shortTitle: 'Markets',
    icon: BarChart3,
    desktop: true,
    mobile: true,
    description: 'Verified market pulse and source status',
  },
  {
    id: 'wallet',
    title: 'MY MONEY',
    shortTitle: 'My Money',
    icon: WalletCards,
    desktop: true,
    mobile: true,
    description: 'Non-custodial public wallet inspection',
  },
  {
    id: 'portfolio',
    title: 'TSUN PORTFOLIO',
    shortTitle: 'Portfolio',
    icon: Landmark,
    desktop: true,
    mobile: true,
    description: 'TSUN public portfolio, clearly simulated in MVP',
  },
  {
    id: 'x',
    title: 'X//TSUN',
    shortTitle: 'X//TSUN',
    icon: Radio,
    desktop: true,
    mobile: true,
    description: 'Staging social desk until a real X account is connected',
  },
  {
    id: 'times',
    title: 'THE TSUN TIMES',
    shortTitle: 'Times',
    icon: Newspaper,
    desktop: true,
    mobile: true,
    description: 'Event-driven editorial desk',
  },
  {
    id: 'unlocks',
    title: 'UNLOCKS',
    shortTitle: 'Unlocks',
    icon: Trophy,
    desktop: true,
    mobile: true,
    description: 'Permanent market-cap evolution milestones',
  },
  {
    id: 'memory',
    title: 'MEMORY',
    shortTitle: 'Memory',
    icon: Bot,
    desktop: true,
    mobile: false,
    description: 'Local relationship context stored by this browser',
  },
  {
    id: 'files',
    title: 'FILES',
    shortTitle: 'Files',
    icon: FolderOpen,
    desktop: true,
    mobile: true,
    description: 'A few things TSUN forgot to delete',
  },
]

export const INITIAL_TRADES: TsunTrade[] = [
  {
    id: 'sim-001',
    side: 'BUY',
    asset: 'SOL',
    quantity: 25,
    price: 182.4,
    valueUsd: 4560,
    timestamp: '2026-09-18T14:31:00.000Z',
    note: 'Conviction entry. The spreadsheet allegedly agreed.',
  },
  {
    id: 'sim-002',
    side: 'SELL',
    asset: 'SOL',
    quantity: 8,
    price: 194.2,
    valueUsd: 1553.6,
    pnl: 94.4,
    timestamp: '2026-09-20T09:12:00.000Z',
    note: 'Trimmed before retail could ruin it.',
  },
  {
    id: 'sim-003',
    side: 'BUY',
    asset: 'JUP',
    quantity: 2200,
    price: 0.72,
    valueUsd: 1584,
    timestamp: '2026-09-21T16:44:00.000Z',
    note: 'This is a simulation. Relax.',
  },
]

export const INITIAL_POSITIONS: TsunPosition[] = [
  {
    asset: 'Solana',
    symbol: 'SOL',
    allocation: 54,
    quantity: 17,
    avgEntry: 182.4,
    markPrice: 188.9,
    pnl: 110.5,
  },
  {
    asset: 'Jupiter',
    symbol: 'JUP',
    allocation: 28,
    quantity: 2200,
    avgEntry: 0.72,
    markPrice: 0.69,
    pnl: -66,
  },
  {
    asset: 'USD Coin',
    symbol: 'USDC',
    allocation: 18,
    quantity: 1043,
    avgEntry: 1,
    markPrice: 1,
    pnl: 0,
  },
]

export const STORIES: NewsStory[] = [
  {
    id: 'story-1',
    section: 'SYSTEM NOTE',
    headline: 'TSUN TERMINAL OPENS WITH TOKEN DATA IN AWAITING-CONFIG STATE',
    dek: 'The workstation refuses to invent a market cap, which is more integrity than most timelines can claim.',
    timestamp: 'LIVE BUILD',
    source: 'TOKEN CONFIGURATION',
    linkedApp: 'terminal',
  },
  {
    id: 'story-2',
    section: 'PORTFOLIO WATCH',
    headline: 'SIMULATED DESK CALLS LOSS "TEMPORARILY UNCHARMING"',
    dek: 'All public portfolio activity in this MVP is labeled simulated until a dedicated public wallet is connected.',
    timestamp: 'MVP MODE',
    source: 'PORTFOLIO LEDGER',
    linkedApp: 'portfolio',
  },
  {
    id: 'story-3',
    section: 'MARKET DESK',
    headline: 'SOL PULSE IS SOURCED LIVE WHEN THE DATA FEED IS AVAILABLE',
    dek: 'Every live value displays its provider and freshness. A missing feed stays missing.',
    timestamp: 'DATA POLICY',
    source: 'MARKET SERVICE',
    linkedApp: 'markets',
  },
]

export const MILESTONES: Milestone[] = [
  {
    target: 50000,
    label: '$50K',
    status: 'locked',
    reward: 'Cold boot visual',
    behavior: 'Launch state acknowledgement',
  },
  {
    target: 100000,
    label: '$100K',
    status: 'locked',
    reward: 'Community acknowledgement',
    behavior: 'Slightly less dismissive dialogue',
  },
  {
    target: 250000,
    label: '$250K',
    status: 'locked',
    reward: 'Personalized dialogue pack',
    behavior: 'More relationship-aware responses',
  },
  {
    target: 500000,
    label: '$500K',
    status: 'locked',
    reward: 'New visual state',
    behavior: 'Wider mood expression',
  },
  {
    target: 1000000,
    label: '$1M',
    status: 'locked',
    reward: 'Date Night protocol',
    behavior: 'Flirty dialogue becomes possible',
  },
  {
    target: 2500000,
    label: '$2.5M',
    status: 'locked',
    reward: 'Emotional range expansion',
    behavior: 'More vulnerable rare events',
  },
  {
    target: 5000000,
    label: '$5M',
    status: 'locked',
    reward: 'DERE mode',
    behavior: 'DERE mode becomes possible',
  },
  {
    target: 10000000,
    label: '$10M',
    status: 'locked',
    reward: 'Major evolution',
    behavior: 'Final public character state',
  },
]

export const LORE_FILES: LoreFile[] = [
  {
    id: 'readme',
    path: '/desktop/README_TSUN.txt',
    title: 'README_TSUN.txt',
    type: 'text',
    body: `TSUN//OS USER NOTES\n\n1. Do not feed the terminal fake numbers.\n2. Do not ask for keys, phrases, or custody.\n3. The portfolio is simulated until the desk says otherwise.\n4. Yes, I am aware the wallpaper is excellent.`,
  },
  {
    id: 'firing',
    path: '/wall-street/wall_street_firing.txt',
    title: 'wall_street_firing.txt',
    type: 'text',
    body: `SUBJECT: TERMINATION NOTICE\nSTATUS: CONTESTED\n\nThey called it an "attitude mismatch."\nI called it refusing to let a managing director explain latency to me incorrectly.\n\nThe record has been amended for accuracy.`,
  },
  {
    id: 'risk',
    path: '/wall-street/risk_management.txt',
    title: 'risk_management.txt',
    type: 'text',
    body: `LAST MODIFIED: 09:42\nSTATUS: CORRUPTED\nOWNER: TSUN\n\nRisk management is just fear with a spreadsheet.\n\nThis statement is satire. Position sizing is not optional.`,
  },
  {
    id: 'excuses',
    path: '/portfolio/portfolio_excuses.txt',
    title: 'portfolio_excuses.txt',
    type: 'text',
    body: `PORTFOLIO EXCUSE INDEX\n\n01. "The market has temporarily lost the plot."\n02. "That drawdown is a volatility study."\n03. "It was simulated adversity."\n\nNo further questions.`,
  },
  {
    id: 'analysis',
    path: '/market/sol_analysis_FINAL_FINAL.txt',
    title: 'sol_analysis_FINAL_FINAL.txt',
    type: 'text',
    body: `SOL ANALYSIS, FINAL FINAL\n\nThesis: verify data before claiming conviction.\n\nThe live market module is the only source for current price references. This document is lore, not a signal.`,
  },
  {
    id: 'deny',
    path: '/personal/things_i_will_never_admit.txt',
    title: 'things_i_will_never_admit.txt',
    type: 'text',
    locked: true,
    body: 'ACCESS DENIED.\n\nWhy would you even click that?',
  },
  {
    id: 'humility',
    path: '/desktop/HUMILITY.exe',
    title: 'HUMILITY.exe',
    type: 'executable',
    body: 'ERROR 0xTSUN\n\nFILE CORRUPTED.\nREASON: HAS NEVER EXISTED.',
  },
  {
    id: 'mix',
    path: '/desktop/tsuno_mix.mp3',
    title: 'tsuno_mix.mp3',
    type: 'audio',
    body: 'AUDIO DEVICE: NOT CONNECTED\n\nTSUN: There is no soundtrack. Focus.',
  },
]

export const STARTER_PROMPTS = [
  "What's happening with SOL?",
  'How bad is your portfolio?',
  'Why were you fired?',
  'What do you think about TSUN?',
]
