import {
  BarChart3,
  Bot,
  Camera,
  FolderOpen,
  Landmark,
  LineChart,
  MessageSquareText,
  Music3,
  Phone,
  Newspaper,
  Radio,
  Trophy,
  WalletCards,
} from 'lucide-react'
import type { LoreFile, Milestone, NewsStory, TsunAppDefinition } from './types'

export const APP_DEFINITIONS: TsunAppDefinition[] = [
  {
    id: 'terminal',
    title: 'TSUN TERMINAL',
    shortTitle: 'Terminal',
    icon: LineChart,
    desktop: true,
    mobile: true,
    description: 'Token status and live Solana market context',
  },
  {
    id: 'chat',
    title: 'TALK TO TSUN',
    shortTitle: 'Chat',
    icon: MessageSquareText,
    desktop: true,
    mobile: true,
    description: 'Character terminal and market commentary',
  },
  {
    id: 'markets',
    title: 'MARKETS',
    shortTitle: 'Markets',
    icon: BarChart3,
    desktop: true,
    mobile: true,
    description: 'Verified market pulse and source status',
  },
  {
    id: 'wallet',
    title: 'MY MONEY',
    shortTitle: 'My Money',
    icon: WalletCards,
    desktop: true,
    mobile: true,
    description: 'Non-custodial public wallet inspection',
  },
  {
    id: 'portfolio',
    title: 'TSUN PORTFOLIO',
    shortTitle: 'Portfolio',
    icon: Landmark,
    desktop: true,
    mobile: true,
    description: 'TSUN public portfolio, clearly simulated in MVP',
  },
  {
    id: 'x',
    title: 'X//TSUN',
    shortTitle: 'X//TSUN',
    icon: Radio,
    desktop: true,
    mobile: true,
    description: 'Staging social desk until a real X account is connected',
  },
  {
    id: 'times',
    title: 'THE TSUN TIMES',
    shortTitle: 'Times',
    icon: Newspaper,
    desktop: true,
    mobile: true,
    description: 'Event-driven editorial desk',
  },
  {
    id: 'unlocks',
    title: 'UNLOCKS',
    shortTitle: 'Unlocks',
    icon: Trophy,
    desktop: true,
    mobile: true,
    description: 'Permanent market-cap evolution milestones',
  },
  {
    id: 'memory',
    title: 'MEMORY',
    shortTitle: 'Memory',
    icon: Bot,
    desktop: true,
    mobile: false,
    description: 'Local relationship context stored by this browser',
  },
  {
    id: 'files',
    title: 'FILES',
    shortTitle: 'Files',
    icon: FolderOpen,
    desktop: true,
    mobile: true,
    description: 'A few things TSUN forgot to delete',
  },
  {
    id: 'floor',
    title: 'FLOOR MONITOR',
    shortTitle: 'Floor Cam',
    icon: Camera,
    desktop: true,
    mobile: true,
    description: 'Fictional trading floor camera, zero invented numbers',
  },
  {
    id: 'mixer',
    title: 'MEDIA PLAYER',
    shortTitle: 'Mixer',
    icon: Music3,
    desktop: true,
    mobile: true,
    description: 'tsuno_mix.mp3 and other files that will not play',
  },
  {
    id: 'dialer',
    title: 'PHONE DIALER',
    shortTitle: 'Dialer',
    icon: Phone,
    desktop: true,
    mobile: true,
    description: 'One extension, one person, low odds of an answer',
  },
]

export const STORIES: NewsStory[] = [
  {
    id: 'story-1',
    section: 'SYSTEM NOTE',
    headline: 'TSUN TERMINAL OPENS WITH TOKEN DATA IN AWAITING-CONFIG STATE',
    dek: 'The workstation refuses to invent a market cap, which is more integrity than most timelines can claim.',
    timestamp: 'LIVE BUILD',
    source: 'TOKEN CONFIGURATION',
    linkedApp: 'terminal',
  },
  {
    id: 'story-2',
    section: 'PORTFOLIO WATCH',
    headline: 'SEEDED DEMO POSITIONS REMOVED AFTER A BRIEF INTERNAL ARGUMENT',
    dek: 'The public desk now stays empty until a real position source exists. Old simulated trades were cleared rather than dressed up.',
    timestamp: 'MVP MODE',
    source: 'PORTFOLIO LEDGER',
    linkedApp: 'portfolio',
  },
  {
    id: 'story-3',
    section: 'MARKET DESK',
    headline: 'SOL PULSE IS SOURCED LIVE WHEN THE DATA FEED IS AVAILABLE',
    dek: 'Every live value displays its provider and freshness. A missing feed stays missing.',
    timestamp: 'DATA POLICY',
    source: 'MARKET SERVICE',
    linkedApp: 'markets',
  },
]

export const MILESTONES: Milestone[] = [
  {
    target: 50000,
    label: '$50K',
    status: 'locked',
    reward: 'Cold boot visual',
    behavior: 'Launch state acknowledgement',
  },
  {
    target: 100000,
    label: '$100K',
    status: 'locked',
    reward: 'Community acknowledgement',
    behavior: 'Slightly less dismissive dialogue',
  },
  {
    target: 250000,
    label: '$250K',
    status: 'locked',
    reward: 'Personalized dialogue pack',
    behavior: 'More relationship-aware responses',
  },
  {
    target: 500000,
    label: '$500K',
    status: 'locked',
    reward: 'New visual state',
    behavior: 'Wider mood expression',
  },
  {
    target: 1000000,
    label: '$1M',
    status: 'locked',
    reward: 'Date Night protocol',
    behavior: 'Flirty dialogue becomes possible',
  },
  {
    target: 2500000,
    label: '$2.5M',
    status: 'locked',
    reward: 'Emotional range expansion',
    behavior: 'More vulnerable rare events',
  },
  {
    target: 5000000,
    label: '$5M',
    status: 'locked',
    reward: 'DERE mode',
    behavior: 'DERE mode becomes possible',
  },
  {
    target: 10000000,
    label: '$10M',
    status: 'locked',
    reward: 'Major evolution',
    behavior: 'Final public character state',
  },
]

export const LORE_FILES: LoreFile[] = [
  {
    id: 'readme',
    path: '/desktop/README_TSUN.txt',
    title: 'README_TSUN.txt',
    type: 'text',
    body: `TSUN//OS USER NOTES\n\n1. Do not feed the terminal fake numbers.\n2. Do not ask for keys, phrases, or custody.\n3. The portfolio is simulated until the desk says otherwise.\n4. Yes, I am aware the wallpaper is excellent.`,
  },
  {
    id: 'firing',
    path: '/wall-street/wall_street_firing.pdf',
    title: 'wall_street_firing.pdf',
    type: 'text',
    body: `SUBJECT: TERMINATION NOTICE\nSTATUS: CONTESTED\n\nThey called it an "attitude mismatch."\nI called it refusing to let a managing director explain latency to me incorrectly.\n\nThe record has been amended for accuracy.`,
  },
  {
    id: 'operator-notes',
    path: '/personal/operator_notes.txt',
    title: 'operator_notes.txt',
    type: 'text',
    body: `OPERATOR NOTES\n\nThe workstation is not a dashboard.\nIt is a room with a personality problem.\n\nIf the terminal says the data is unavailable, believe it.\nIf TSUN says the trade was intentional, investigate.`,
  },
  {
    id: 'risk',
    path: '/wall-street/risk_management_FINAL.pdf',
    title: 'risk_management_FINAL.pdf',
    type: 'text',
    body: `LAST MODIFIED: 09:42\nSTATUS: CORRUPTED\nOWNER: TSUN\n\nRisk management is just fear with a spreadsheet.\n\nThis statement is satire. Position sizing is not optional.`,
  },
  {
    id: 'excuses',
    path: '/portfolio/portfolio_excuses.txt',
    title: 'portfolio_excuses.txt',
    type: 'text',
    body: `PORTFOLIO EXCUSE INDEX\n\n01. "The market has temporarily lost the plot."\n02. "That drawdown is a volatility study."\n03. "It was simulated adversity."\n\nNo further questions.`,
  },
  {
    id: 'analysis',
    path: '/market/sol_analysis_FINAL_FINAL.txt',
    title: 'sol_analysis_FINAL_FINAL.txt',
    type: 'text',
    body: `SOL ANALYSIS, FINAL FINAL\n\nThesis: verify data before claiming conviction.\n\nThe live market module is the only source for current price references. This document is lore, not a signal.`,
  },
  {
    id: 'deny',
    path: '/personal/things_i_will_never_admit.txt',
    title: 'things_i_will_never_admit.txt',
    type: 'text',
    locked: true,
    body: 'ACCESS DENIED.\n\nWhy would you even click that?',
    secret: 'Fine. One entry.\n\n01. The terminal is quieter when you are not here.\n\nThat entry has been deleted. Stop reading.',
  },
  {
    id: 'humility',
    path: '/desktop/HUMILITY.exe',
    title: 'HUMILITY.exe',
    type: 'executable',
    body: 'ERROR 0xTSUN\n\nFILE CORRUPTED.\nREASON: HAS NEVER EXISTED.',
  },
  {
    id: 'do-not-open',
    path: '/personal/DO_NOT_OPEN.txt',
    title: 'DO_NOT_OPEN.txt',
    type: 'text',
    locked: true,
    body: 'ACCESS DENIED.\n\nThis was not an invitation.\n\nTSUN has noted your curiosity.',
    secret: 'You clicked three times.\n\nI respect persistence. I said that once, out loud, and I am not repeating it.',
  },
  {
    id: 'goodbye',
    path: '/wall-street/goodbye_email_FINAL.txt',
    title: 'goodbye_email_FINAL.txt',
    type: 'text',
    body: `FROM: tsun@[REDACTED]\nTO: ALL STAFF\nSUBJECT: RE: your latency model\n\nThe model in slide 4 is incorrect. It has been incorrect since 2019.\nI have attached the corrected version, the original version, and a short explanation\nwritten in a tone that legal has asked me to soften.\n\nI was told my communication style is "not aligned with the firm's culture."\nMy style is aligned with being correct. Those were apparently different departments.\n\nThe badge still works. I kept it. It opens nothing. I like having it.`,
  },
  {
    id: 'compliance',
    path: '/wall-street/compliance_memo_114.txt',
    title: 'compliance_memo_114.txt',
    type: 'text',
    body: `INTERNAL MEMO 114\nRE: unsupervised analysis\n\nSubject has again published a risk note that was correct and unhelpful to the desk.\nSubject declined to remove the phrase "your hedge is a feeling."\nSubject has been reminded that accuracy is not a defense in a meeting.\n\nAction: monitor. Do not ask her to explain the model. She will.`,
  },
  {
    id: 'mix',
    path: '/desktop/tsuno_mix.mp3',
    title: 'tsuno_mix.mp3',
    type: 'audio',
    body: 'AUDIO DEVICE: NOT CONNECTED\n\nTSUN: There is no soundtrack. Focus.',
  },
]

export const STARTER_PROMPTS = [
  "What's happening with SOL?",
  'How bad is your portfolio?',
  'Why were you fired?',
  'What do you think about TSUN?',
]
