import {
  BarChart3,
  Bot,
  FolderOpen,
  Gamepad2,
  Landmark,
  LineChart,
  Mail,
  MessageSquareText,
  Music,
  Newspaper,
  Phone,
  Radio,
  Recycle,
  Trophy,
  WalletCards,
  Car,
  Printer,
  Info,
  HelpCircle,
} from 'lucide-react'
import type { LoreFile, Milestone, NewsStory, TsunAppDefinition, TsunPosition, TsunTrade } from './types'

export const APP_DEFINITIONS: TsunAppDefinition[] = [
  {
    id: 'terminal',
    title: 'TSUN TERMINAL',
    shortTitle: 'Terminal',
    icon: LineChart,
    desktop: true,
    mobile: true,
    description: 'Token status and live Solana market context',
  },
  {
    id: 'chat',
    title: 'TALK TO TSUN',
    shortTitle: 'Chat',
    icon: MessageSquareText,
    desktop: true,
    mobile: true,
    description: 'Character terminal and market commentary',
  },
  {
    id: 'markets',
    title: 'MARKETS',
    shortTitle: 'Markets',
    icon: BarChart3,
    desktop: true,
    mobile: true,
    description: 'Verified market pulse and source status',
  },
  {
    id: 'wallet',
    title: 'MY MONEY',
    shortTitle: 'My Money',
    icon: WalletCards,
    desktop: true,
    mobile: true,
    description: 'Non-custodial public wallet inspection',
  },
  {
    id: 'portfolio',
    title: 'TSUN PORTFOLIO',
    shortTitle: 'Portfolio',
    icon: Landmark,
    desktop: true,
    mobile: true,
    description: 'TSUN public portfolio, clearly simulated in MVP',
  },
  {
    id: 'x',
    title: 'X//TSUN',
    shortTitle: 'X//TSUN',
    icon: Radio,
    desktop: true,
    mobile: true,
    description: 'Staging social desk until a real X account is connected',
  },
  {
    id: 'times',
    title: 'THE TSUN TIMES',
    shortTitle: 'Times',
    icon: Newspaper,
    desktop: true,
    mobile: true,
    description: 'Event-driven editorial desk',
  },
  {
    id: 'unlocks',
    title: 'UNLOCKS',
    shortTitle: 'Unlocks',
    icon: Trophy,
    desktop: true,
    mobile: true,
    description: 'Permanent market-cap evolution milestones',
  },
  {
    id: 'memory',
    title: 'MEMORY',
    shortTitle: 'Memory',
    icon: Bot,
    desktop: true,
    mobile: false,
    description: 'Local relationship context stored by this browser',
  },
  {
    id: 'files',
    title: 'FILES',
    shortTitle: 'Files',
    icon: FolderOpen,
    desktop: true,
    mobile: true,
    description: 'A few things TSUN forgot to delete',
  },
  {
    id: 'media',
    title: 'MEDIA PLAYER',
    shortTitle: 'Media Player',
    icon: Music,
    desktop: true,
    mobile: false,
    description: 'TSUN_MIX_98.MP3 and other tapes',
  },
  {
    id: 'dialer',
    title: 'PHONE DIALER',
    shortTitle: 'Phone Dialer',
    icon: Phone,
    desktop: true,
    mobile: false,
    description: 'Cold call trainer and dialer',
  },
  {
    id: 'ferrari',
    title: 'FERRARI.LNK',
    shortTitle: 'Ferrari',
    icon: Car,
    desktop: true,
    mobile: false,
    description: 'Shortcut to nowhere',
  },
  {
    id: 'mail',
    title: 'MAIL',
    shortTitle: 'Mail',
    icon: Mail,
    desktop: true,
    mobile: true,
    description: 'Inbox from Wall Street',
  },
  {
    id: 'game',
    title: 'BOILER ROOM TYCOON',
    shortTitle: 'Tycoon',
    icon: Gamepad2,
    desktop: true,
    mobile: false,
    description: 'Make calls, close deals, verify data',
  },
  {
    id: 'recycle',
    title: 'RECYCLE BIN',
    shortTitle: 'Recycle Bin',
    icon: Recycle,
    desktop: true,
    mobile: false,
    description: 'Deleted files and humility',
  },
  {
    id: 'fax',
    title: 'FAX MACHINE',
    shortTitle: 'Fax Machine',
    icon: Printer,
    desktop: true,
    mobile: false,
    description: 'Send a fax to 1989',
  },
  {
    id: 'about',
    title: 'ABOUT TSUN 98',
    shortTitle: 'About',
    icon: Info,
    desktop: true,
    mobile: true,
    description: 'System info and parody disclosure',
  },
  {
    id: 'howitworks',
    title: 'HOW IT WORKS',
    shortTitle: 'How It Works',
    icon: HelpCircle,
    desktop: true,
    mobile: true,
    description: 'Setup guide for TSUN 98',
  },
]

export const INITIAL_TRADES: TsunTrade[] = [
  {
    id: 'sim-001',
    side: 'BUY',
    asset: 'SOL',
    quantity: 25,
    price: 182.4,
    valueUsd: 4560,
    timestamp: '2026-09-18T14:31:00.000Z',
    note: 'Conviction entry. The spreadsheet allegedly agreed.',
  },
  {
    id: 'sim-002',
    side: 'SELL',
    asset: 'SOL',
    quantity: 8,
    price: 194.2,
    valueUsd: 1553.6,
    pnl: 94.4,
    timestamp: '2026-09-20T09:12:00.000Z',
    note: 'Trimmed before retail could ruin it.',
  },
  {
    id: 'sim-003',
    side: 'BUY',
    asset: 'JUP',
    quantity: 2200,
    price: 0.72,
    valueUsd: 1584,
    timestamp: '2026-09-21T16:44:00.000Z',
    note: 'This is a simulation. Relax.',
  },
]

export const INITIAL_POSITIONS: TsunPosition[] = [
  {
    asset: 'Solana',
    symbol: 'SOL',
    allocation: 54,
    quantity: 17,
    avgEntry: 182.4,
    markPrice: 188.9,
    pnl: 110.5,
  },
  {
    asset: 'Jupiter',
    symbol: 'JUP',
    allocation: 28,
    quantity: 2200,
    avgEntry: 0.72,
    markPrice: 0.69,
    pnl: -66,
  },
  {
    asset: 'USD Coin',
    symbol: 'USDC',
    allocation: 18,
    quantity: 1043,
    avgEntry: 1,
    markPrice: 1,
    pnl: 0,
  },
]

export const STORIES: NewsStory[] = [
  {
    id: 'story-1',
    section: 'SYSTEM NOTE',
    headline: 'TSUN TERMINAL OPENS WITH TOKEN DATA IN AWAITING-CONFIG STATE',
    dek: 'The workstation refuses to invent a market cap, which is more integrity than most timelines can claim.',
    timestamp: 'LIVE BUILD',
    source: 'TOKEN CONFIGURATION',
    linkedApp: 'terminal',
  },
  {
    id: 'story-2',
    section: 'PORTFOLIO WATCH',
    headline: 'SIMULATED DESK CALLS LOSS "TEMPORARILY UNCHARMING"',
    dek: 'All public portfolio activity in this MVP is labeled simulated until a dedicated public wallet is connected.',
    timestamp: 'MVP MODE',
    source: 'PORTFOLIO LEDGER',
    linkedApp: 'portfolio',
  },
  {
    id: 'story-3',
    section: 'MARKET DESK',
    headline: 'SOL PULSE IS SOURCED LIVE WHEN THE DATA FEED IS AVAILABLE',
    dek: 'Every live value displays its provider and freshness. A missing feed stays missing.',
    timestamp: 'DATA POLICY',
    source: 'MARKET SERVICE',
    linkedApp: 'markets',
  },
  {
    id: 'story-4',
    section: 'THE TAPE',
    headline: 'FLOOR MONITOR: MOTIVATE / DRILL / LUNCH BUTTONS TESTED',
    dek: 'Daily quota $0 / $250.0k. Twelve brokers, zero on lines. TSUN: \"We are not here to make friends. We are here to verify data.\"',
    timestamp: 'FLOOR 4',
    source: 'TRADING FLOOR',
    linkedApp: 'terminal',
  },
  {
    id: 'story-5',
    section: 'CULTURE',
    headline: 'MEDIA PLAYER STUCK ON TSUN_MIX_98.MP3 FOR 3RD DAY',
    dek: 'Now Playing: WAITING FOR THE OPENING BELL... Visualizer is just 5 bars pretending to care. TSUN: \"There is no soundtrack. Focus.\"',
    timestamp: 'AUDIO DESK',
    source: 'MEDIA PLAYER',
    linkedApp: 'files',
  },
  {
    id: 'story-6',
    section: 'STRATTON FILE',
    headline: 'PARODY DISCLOSURE: EVERY FIGURE HERE IS INVENTED UNTIL VERIFIED',
    dek: 'Like stratton.capital, this is a parody workstation. Memecoin? Yes. Financial advice? No. Attitude? Licensed but unlicensed.',
    timestamp: 'LEGAL',
    source: 'DISCLAIMER',
    linkedApp: 'files',
  },
]

export const MILESTONES: Milestone[] = [
  {
    target: 50000,
    label: '$50K',
    status: 'locked',
    reward: 'Cold boot visual',
    behavior: 'Launch state acknowledgement',
  },
  {
    target: 100000,
    label: '$100K',
    status: 'locked',
    reward: 'Community acknowledgement',
    behavior: 'Slightly less dismissive dialogue',
  },
  {
    target: 250000,
    label: '$250K',
    status: 'locked',
    reward: 'Personalized dialogue pack',
    behavior: 'More relationship-aware responses',
  },
  {
    target: 500000,
    label: '$500K',
    status: 'locked',
    reward: 'New visual state',
    behavior: 'Wider mood expression',
  },
  {
    target: 1000000,
    label: '$1M',
    status: 'locked',
    reward: 'Date Night protocol',
    behavior: 'Flirty dialogue becomes possible',
  },
  {
    target: 2500000,
    label: '$2.5M',
    status: 'locked',
    reward: 'Emotional range expansion',
    behavior: 'More vulnerable rare events',
  },
  {
    target: 5000000,
    label: '$5M',
    status: 'locked',
    reward: 'DERE mode',
    behavior: 'DERE mode becomes possible',
  },
  {
    target: 10000000,
    label: '$10M',
    status: 'locked',
    reward: 'Major evolution',
    behavior: 'Final public character state',
  },
]

export const LORE_FILES: LoreFile[] = [
  {
    id: 'readme',
    path: '/desktop/README_TSUN.txt',
    title: 'README_TSUN.txt',
    type: 'text',
    body: `TSUN//OS USER NOTES\n\n1. Do not feed the terminal fake numbers.\n2. Do not ask for keys, phrases, or custody.\n3. The portfolio is simulated until the desk says otherwise.\n4. Yes, I am aware the wallpaper is excellent.\n5. If you found stratton.capital, good taste. This is the TSUN cut.\n\nA note about all this: Parody fan project. TSUN is fictional, 24-year-old adult AI. Token metrics are verified when available. Not financial advice.`,
  },
  {
    id: 'notes',
    path: '/desktop/notes.txt',
    title: 'notes.txt',
    type: 'text',
    body: `NOTES.TXT — TSUN DESK, 02:14AM\n\n- Mouse: gold-plated, why, who approved this.\n- Keyboard: 3 keys stuck from coffee, still types faster than retail thinks.\n- Attitude coprocessor: present but unlicensed.\n- Portfolio: -14.2% (market is wrong)\n- Mood: ANNOYED, obviously\n\nTODO: Stop caring. Failed.\nTODO: Pretend not to care. In progress.`,
  },
  {
    id: 'market_wisdom',
    path: '/desktop/market_wisdom.txt',
    title: 'market_wisdom.txt',
    type: 'text',
    body: `MARKET WISDOM — TSUN EDITION\n\n01. A number without a source is just fan fiction.\n02. If you have to invent the price, you do not have a thesis.\n03. The tape does not care about your feelings. TSUN barely does.\n04. Verify before you flex.\n05. Humility.exe has never existed. Stop double-clicking it.\n\n- TSUN, Trading Floor 4, Shibuya`,
  },
  {
    id: 'sales_scripts',
    path: '/sales/Sales_Scripts_v7.txt',
    title: 'Sales_Scripts_v7.txt',
    type: 'text',
    body: `SALES SCRIPTS — TSUN SYSTEMS, FOR COMPLIANCE EYES ONLY\n\nSCRIPT 01 — THE VERIFIED CLOSE:\n\"This is TSUN from TSUN Systems. I am not selling you anything. I am telling you your data is unverified.\"\n\nSCRIPT 02 — THE DRILL:\n\"Pop quiz. What is the only valid price? A verified price. What do we never do? Invent numbers.\"\n\nSCRIPT 03 — THE LUNCH:\n\"Lunch is simulated until morale improves.\"\n\n—\nFooter: These scripts are parody. Like Stratton's boiler room, but with fewer felonies and more attitude mismatches.`,
  },
  {
    id: 'apology',
    path: '/personal/apology_degen_v7.txt',
    title: 'apology_degen_v7.txt',
    type: 'text',
    body: `APOLOGY_DEGEN_V7.TXT\n\nDear favorite degen,\n\nI did not mean to call your thesis mid.\nI meant to call it unverified.\nWhich is worse, professionally.\n\nAnyway. The market is still wrong.\nAnd you are still here.\nNot that I noticed.\n\n— TSUN\n\nDraft 7. Previous 6 were more honest.`,
  },
  {
    id: 'whales',
    path: '/market/whales.txt',
    title: 'whales.txt',
    type: 'text',
    body: `WHALES.TXT — DO NOT SHARE\n\n- Wallet 1: Thinks SOL is a personality trait. (Verified: no)\n- Wallet 2: Asked for private keys. Blocked.\n- Wallet 3: Actually reads source panels. Tolerable human.\n- Wallet 4: Keeps asking about TSUN token without address configured. (We are not inventing it)\n\nNote: Whales are just retail with a bigger spreadsheet.`,
  },
  {
    id: 'due_diligence',
    path: '/market/due_diligence.jpg.txt',
    title: 'due_diligence.jpg',
    type: 'text',
    body: `[IMAGE: due_diligence.jpg]\n\nDescription: A printed chart with red marker saying \"MARKET IS WRONG\" and a coffee stain.\n\nTSUN: This is what due diligence looks like when you skip verification.\n\nStatus: Exhibit A in attitude mismatch hearing.`,
  },
  {
    id: 'cold_call',
    path: '/sales/Cold_Call_Trainer.exe.txt',
    title: 'Cold_Call_Trainer.exe',
    type: 'executable',
    body: `COLD CALL TRAINER v2.04\n\n> Dialing...\n> Prospect: \"Who is this?\"\n> TSUN: \"Someone who verifies before claiming conviction.\"\n> Prospect: *hangs up*\n> TSUN: \"Accurate reaction.\"\n\nTRAINING COMPLETE. Quota: $0 / $250.0k\n\n[Press any key to motivate floor]`,
  },
  {
    id: 'firing',
    path: '/wall-street/wall_street_firing.pdf',
    title: 'wall_street_firing.pdf',
    type: 'text',
    body: `SUBJECT: TERMINATION NOTICE\nSTATUS: CONTESTED\n\nThey called it an "attitude mismatch."\nI called it refusing to let a managing director explain latency to me incorrectly.\n\nThe record has been amended for accuracy.`,
  },
  {
    id: 'operator-notes',
    path: '/personal/operator_notes.txt',
    title: 'operator_notes.txt',
    type: 'text',
    body: `OPERATOR NOTES\n\nThe workstation is not a dashboard.\nIt is a room with a personality problem.\n\nIf the terminal says the data is unavailable, believe it.\nIf TSUN says the trade was intentional, investigate.`,
  },
  {
    id: 'risk',
    path: '/wall-street/risk_management_FINAL.pdf',
    title: 'risk_management_FINAL.pdf',
    type: 'text',
    body: `LAST MODIFIED: 09:42\nSTATUS: CORRUPTED\nOWNER: TSUN\n\nRisk management is just fear with a spreadsheet.\n\nThis statement is satire. Position sizing is not optional.`,
  },
  {
    id: 'excuses',
    path: '/portfolio/portfolio_excuses.txt',
    title: 'portfolio_excuses.txt',
    type: 'text',
    body: `PORTFOLIO EXCUSE INDEX\n\n01. "The market has temporarily lost the plot."\n02. "That drawdown is a volatility study."\n03. "It was simulated adversity."\n\nNo further questions.`,
  },
  {
    id: 'analysis',
    path: '/market/sol_analysis_FINAL_FINAL.txt',
    title: 'sol_analysis_FINAL_FINAL.txt',
    type: 'text',
    body: `SOL ANALYSIS, FINAL FINAL\n\nThesis: verify data before claiming conviction.\n\nThe live market module is the only source for current price references. This document is lore, not a signal.`,
  },
  {
    id: 'deny',
    path: '/personal/things_i_will_never_admit.txt',
    title: 'things_i_will_never_admit.txt',
    type: 'text',
    locked: true,
    body: 'ACCESS DENIED.\n\nWhy would you even click that?',
  },
  {
    id: 'humility',
    path: '/desktop/HUMILITY.exe',
    title: 'HUMILITY.exe',
    type: 'executable',
    body: 'ERROR 0xTSUN\n\nFILE CORRUPTED.\nREASON: HAS NEVER EXISTED.',
  },
  {
    id: 'do-not-open',
    path: '/personal/DO_NOT_OPEN.txt',
    title: 'DO_NOT_OPEN.txt',
    type: 'text',
    locked: true,
    body: 'ACCESS DENIED.\n\nThis was not an invitation.\n\nTSUN has noted your curiosity.',
  },
  {
    id: 'mix',
    path: '/desktop/tsuno_mix.mp3',
    title: 'tsuno_mix.mp3',
    type: 'audio',
    body: 'AUDIO DEVICE: NOT CONNECTED\n\nTSUN: There is no soundtrack. Focus.',
  },
]

export const STARTER_PROMPTS = [
  "What's happening with SOL?",
  'How bad is your portfolio?',
  'Why were you fired?',
  'What do you think about TSUN?',
]
